create table base_table
(
    created  timestamp,
    modified timestamp,
    owner_id bigint
);

create table employees
(
    employee_id                     bigint       not null primary key,
    employee_no                     integer      not null,
    dept_id                         bigint ,
    zveno                           varchar(20),
    first_name                      varchar(128) not null,
    second_name                     varchar(128) not null,
    full_name                       varchar(128) not null,
    position                        bigint,
    rank                            integer ,
    date_of_employment              timestamp,
    working                         boolean ,
    category_id                     bigint,
    address                         varchar(512),
    home_phone                      varchar(64),
    birthday                        timestamp,
    birthplace                      varchar(256),
    education                       varchar(512),
    edu_year                        integer,
    faculty                         varchar(256),
    specialty                       varchar(64),
    previous_employment             varchar(256),
    note                            varchar(256),
    working_conditions              float8,
    salary                          float8,
    user_login                      varchar(256),
    manager_id                      bigint,
    passport_series                 varchar(8),
    passport_number                 varchar(16),
    personal_number                 varchar(16),
    real_address                    varchar(256),
    family_status                   varchar(256),
    passport_date                   timestamp,
    passport_office                 varchar(256),
    mobile_phone                    varchar(16),
    mobile_phone_zone               varchar(16),
    profession_id1                  bigint,
    profession_id2                  bigint,
    profession_id3                  bigint,
    profession_id4                  bigint,
    profession_id5                  bigint,
    profession_id6                  bigint,
    height                          integer,
    clothing_size                   integer,
    shoe_size                       integer,
    means_of_protection_by_position bigint,
    clothing_size_type_id           bigint,
    gender                          varchar(8)
) inherits (base_table);
