alter table orders alter column order_note type text;
alter table orders alter column oboz_to type varchar(48);
drop table employees;

CREATE TABLE material_cards (
    material_card_id bigint not null primary key ,
    order_number INTEGER,
    detail_number INTEGER,
    tooling_detail_number VARCHAR(32) NOT NULL,
    detail_name VARCHAR(64),
    material VARCHAR(100),
    forging_operation VARCHAR(30),
    detail_dimensions VARCHAR(20),
    quantity REAL NOT NULL,
    details_quantity REAL NOT NULL,
    milling_processing VARCHAR(15),
    planing_processing VARCHAR(30),
    grinding_processing VARCHAR(50),
    milling_time REAL,
    planing_time REAL,
    grinding_time REAL,
    blank_weight REAL,
    total_weight REAL,
    additional_for_work_order BOOLEAN,
    tech_edit_date TIMESTAMP,
    warehouse INTEGER,
    unit_code INTEGER,
    material_code INTEGER,
    annealing BOOLEAN,
    term VARCHAR(50),
    planing_term VARCHAR(50),
    detail_weight DOUBLE PRECISION,
    ordered BOOLEAN,
    material2 VARCHAR(100),
    card_num INTEGER
) inherits (base_table);

create table employees (
    employee_id bigint not null primary key,
    personnel_number integer not null,
    department integer not null,
    team varchar(10),
    first_name varchar(33) not null,
    last_name varchar(50) not null,
    full_name varchar(50) not null,
    position_title integer,
    grade integer,
    operation varchar(21),
    performed_operations varchar(90),
    hire_date timestamp,
    is_working boolean,
    category integer not null,
    address varchar(90),
    home_phone varchar(50),
    birth_date timestamp,
    birth_place varchar(255),
    education_place varchar(100),
    graduation_year integer,
    faculty varchar(70),
    specialization varchar(50),
    previous_workplace varchar(255),
    notes text,
    working_conditions double precision,
    labor_coefficient double precision,
    worker_sum integer,
    user_login varchar(254),
    supervisor integer,
    passport_series varchar(2),
    residential_address varchar(200),
    family_status varchar(255),
    passport_number varchar(7),
    passport_date timestamp,
    passport_office varchar(200),
    personal_number varchar(16),
    mobile_phone_zone varchar(2),
    mobile_phone varchar(9),
    profession1 integer,
    profession2 integer,
    profession3 integer,
    profession4 integer,
    profession5 integer,
    profession6 integer,
    height integer,
    clothing_size integer,
    shoe_size integer,
    ppe_profession integer,
    size_code integer,
    gender varchar(5)
) inherits (base_table);