CREATE TABLE order_execution (
    order_execution_id bigserial not null primary key,
    order_id bigint,
    detail_number int,
    batch int NOT NULL,
    operation_number int NOT NULL,
    part int NOT NULL,
    operation VARCHAR(21) NOT NULL,
    operation_content TEXT,
    time_norm REAL,
    executor VARCHAR(50),
    machine_coefficient BOOLEAN,
    initial_quantity REAL,
    work_start_date TIMESTAMP,
    final_quantity REAL,
    work_end_date TIMESTAMP,
    first_shift INTEGER,
    second_shift INTEGER,
    midnight_shift INTEGER,
    note VARCHAR(200),
    log TEXT,
    prog_start TIMESTAMP,
    prog_end TIMESTAMP,
    programmer VARCHAR(50),
    submitted_to_qc TIMESTAMP,
    urgent_qc BOOLEAN,
    prog_type INTEGER,
    erosion_type BOOLEAN,
    prog_time TIMESTAMP
) inherits (base_table);